### PR TITLE
Cleanup bot main botkit, clean up business logic

### PR DESCRIPTION
**Pull request by mrking**
- Broke out the reporting function into new a class. 
- Cleaned up the main a bit, still unsure how to go about testing it

### CODE REVIEW

**Comment by tyronetan** [comment]
I think we need to decide on a coding pattern for catching reject streams from Promises. In some of our codes, we follow the ES6 convention to create anonymous functions to branch off from when the Promise rejects an output. I personally think this manner of coding violates the reason why Promises are considered the better coding convention as it potentially creates a nested function look that is hard to read.

One of the articles I have read prescribes a catch all if there's not a need for nested promises or nested branching from reject streams.

**Comment by mrking** [comment]
I think its situational and not a particular coding pattern that needs to be practiced. The two function differently. Catching a reject in the then in not the same as a catch because a catch is for all errors in the chain.

**Review by tyronetan — APPROVED** [review]
We just need to write a test code for RunUserHoursCheck. A suggested test case would be to create a toggl account for our bot and manipulate its timers. After that, we can have our bot listen to the generated report and write the test results based on the output

**Comment by mrking** [comment]
Open issue for it!

**Comment by tyronetan** [comment]
I think that while it is situational, there are some cases where there is no nesting of promises going on but one case leads to a catch while another leads to an anonymous function

**Pull request merged**
